from django.urls import path
from . import views
urlpatterns = [path('new',views.test,name='test'),
    path('login/', views.login, name='login'),
    path('log',views.log),
    path('login/signup/domestic/kerala/buynow/',views.buynow),
    path('login/signup/domestic/kashmir/buynow/',views.buynow),
    path('login/signup/domestic/rajasthan/buynow/',views.buynow),
    path('login/signup/international/dubai/buynow/',views.buynow),
    path('login/signup/international/europe/buynow/',views.buynow),
    path('login/signup/international/singapore/buynow/',views.buynow),
    path('login/signup/',views.welcome,name='welcome'),
    path('login/signup/domestic/',views.domestic,name='domestic'),
    path('login/signup/international/',views.international,name='international'),
    path('login/signup/domestic/kerala/',views.kerala,name='kerala'),
    path('login/signup/domestic/kashmir/',views.Kashmir,name='Kashmir'),
    path('login/signup/domestic/rajasthan/',views.Rajasthan,name='Rajasthan'),
    path('login/signup/international/dubai/',views.Dubai,name='Dubai'),
    path('login/signup/international/singapore/',views.Singapore,name='Singapore'),
    path('login/signup/international/europe/',views.Europe,name='Europe'),
    path('login/signup/gallery/',views.gallery,name='gallery'),
    path('login/signup/about/',views.about,name='about'),
    path('login/sign/',views.signup,name='sign'),
    path('login/sign',views.login,name='login'),
    path('sign',views.sign,name='sign'),
    path('show/',views.show),
    path('edit/<int:id>',views.edit),
    path('edcode/<int:id>',views.edcode),
]
path('loginf/', views.loginf, name='loginf'),